fix: engine build crashes when changing tooling versions (#710)
Working on bumping elixir + erlang versions I kept hitting errors like
this one:

```
LSP[expert] [engine] Engine build failed for engine::49905813.
Build script exited with status: 1

15:52:13.161 [error] beam/beam_load.c(604): Error loading function 'Elixir.Hex.State':print_invalid_config_error/2:
please re-compile this module with an Erlang/OTP 29 compiler or update your Erlang/OTP version
15:52:13.165 [error] beam/beam_load.c(604): Error loading function 'Elixir.Hex.State':print_invalid_config_error/2:
please re-compile this module with an Erlang/OTP 29 compiler or update your Erlang/OTP version
15:52:13.167 [notice] Application hex exited: exited in: Hex.Application.start(:normal, [])
** (EXIT) an exception was raised:
** (ArgumentError) The module Hex.State was given as a child to a supervisor but it does not exist
(elixir 1.20.0) lib/supervisor.ex:827: Supervisor.init_child/1
(elixir 1.20.0) lib/enum.ex:1725: Enum."-map/2-lists^map/1-1-"/2
(elixir 1.20.0) lib/enum.ex:1725: Enum."-map/2-lists^map/1-1-"/2
(elixir 1.20.0) lib/supervisor.ex:813: Supervisor.init/2
(elixir 1.20.0) lib/supervisor.ex:737: Supervisor.start_link/2
(kernel 11.0.1) application_master.erl:299: :application_master.start_it_old/4
15:52:13.168 [notice] Application inets exited: :stopped
15:52:13.169 [notice] Application ssl exited: :stopped
15:52:13.169 [notice] Application public_key exited: :stopped
15:52:13.169 [notice] Application asn1 exited: :stopped
15:52:13.169 [notice] Application crypto exited: :stopped
==> engine
Could not start Hex. Try fetching a new version with "mix local.hex" or uninstalling it with "mix archive.uninstall hex.ez"
** (MatchError) no match of right hand side value:
{:error,
{:hex,
{:bad_return,
{{Hex.Application, :start, [:normal, []]},
{:EXIT,
{%ArgumentError{
message: "The module Hex.State was given as a child to a supervisor but it does not exist"
},
[
{Supervisor, :init_child, 1, [file: ~c"lib/supervisor.ex", line: 827]},
{Enum, :"-map/2-lists^map/1-1-", 2, [file: ~c"lib/enum.ex", line: 1725]},
{Enum, :"-map/2-lists^map/1-1-", 2, [file: ~c"lib/enum.ex", line: 1725]},
{Supervisor, :init, 2, [file: ~c"lib/supervisor.ex", line: 813]},
{Supervisor, :start_link, 2, [file: ~c"lib/supervisor.ex", line: 737]},
{:application_master, :start_it_old, 4,
[file: ~c"application_master.erl", line: 299]}
]}}}}}}
(hex 2.3.1) lib/hex.ex:5: Hex.start/0
(mix 1.20.0) lib/mix/hex.ex:64: Mix.Hex.start/0
(mix 1.20.0) lib/mix/dep/loader.ex:196: Mix.Dep.Loader.with_scm_and_app/5
(mix 1.20.0) lib/mix/dep/loader.ex:147: Mix.Dep.Loader.to_dep/4
(elixir 1.20.0) lib/enum.ex:1725: Enum."-map/2-lists^map/1-1-"/2
(mix 1.20.0) lib/mix/dep/loader.ex:377: Mix.Dep.Loader.mix_children/3
(mix 1.20.0) lib/mix/dep/loader.ex:330: anonymous fn/5 in Mix.Dep.Loader.mix_dep/3
(mix 1.20.0) lib/mix/project.ex:557: Mix.Project.in_project/4 
```

I'm not entirely sure if this happened because we started setting some
vars to empty strings instead of removing them, or if it was the missing
env vars I added to the scrub list, but the changes here stopped the
engine build errors for me when changing elixir/erlang versions on my
projects